### ISSUE TITLE
Doesn't work in a react development environment

### ISSUE THREAD

**Issue by meetmangukiya** [heineiuo/isomorphic-ws#14]
Maybe it has something to do with using a development server which runs on node and makes isomorphic-ws fail to detect that it is eventually running inside a browser? Not sure.

**Comment by heineiuo** [comment]
@meetmangukiya which development server, CRA?

**Comment by meetmangukiya** [comment]
Yes

**Comment by JohannesHoffmann** [comment]
I am running the same and it is working like expected.
