### ISSUE TITLE
Can't construct WebSocket

### ISSUE THREAD

**Issue by kirillt** [heineiuo/isomorphic-ws#15]
This code fails:
```
const WebSocket = require("isomorphic-ws");
const ws = new WebSocket("wss://echo.websocket.org/", {
    origin: "https://websocket.org"
});
```

Firefox:
```
SyntaxError: An invalid or illegal string was specified
```

Chromium-based browser:
```
Uncaught DOMException: Failed to construct 'WebSocket': The subprotocol '[object Object]' is invalid.
    at Object.76.isomorphic-ws (https://localhost:9966/index.js:33990:12)
    at o (https://localhost:9966/index.js:1:265)
    at r (https://localhost:9966/index.js:1:431)
    at https://localhost:9966/index.js:1:460
```

**Comment by julien-f** [comment]
How do you bundle your code?

**Comment by kirillt** [comment]
@julien-f with Babel and WebPack
Here is my `package.json`:
```
{
  "private": true,
  "scripts": {
    "build": "babel src -d lib; webpack",
    "start": "budo dist/index.js:index.js --ssl --cert ...  --key ..."
  },
  "dependencies": {
    "isomorphic-ws": "^4.0.1",
    "ws": "^7.2.5"
  },
  "devDependencies": {
    "@babel/cli": "^7.8.4",
    "@babel/core": "^7.9.6",
    "@babel/preset-env": "^7.9.6",
    "budo": "^11.6.3",
    "webpack": "^4.43.0",
    "webpack-cli": "^3.3.11"
  },
  "browserslist": "> 0.25%, not dead"
}
```

**Comment by julien-f** [comment]
I suspect that your code is using the Node implementation provided by `node.js` instead of the browser implementation provided by `browser.js`.

Make sure that your bundler supports the `browser` entry in `package.json`: https://github.com/heineiuo/isomorphic-ws/blob/0a0d1692744dd26fc1b58ca24d4ff2d051d27be0/package.json#L6

**Comment by kirillt** [comment]
Thank you @julien-f but this doesn't work for me. I tried to call `src/index.js` directly bypassing bundlers, but the result is the same. Is there a minimal example working in browser which uses this library? I agree, the issue is quite weird since I don't see any dependencies to satisfy except `ws`.

**Comment by julien-f** [comment]
In browser, the module should use the code in `browser.js`, you can try by directly requiring/importing `'isomorphic-ws/browser.js'`.

This module is automatically selected if the bundler supports the `browser` entry in `package.json`.
