### ISSUE TITLE
Error:  'WebSocket': The subprotocol '[object Object]' is invalid.\n    at RPC.createSocket 

### ISSUE THREAD

**Issue by sshelake25** [heineiuo/isomorphic-ws#16]
Error during communication with engine {"stack":"Error: Failed to construct 'WebSocket': The subprotocol '[object Object]' is invalid.\n    at RPC.createSocket (http://localhost:4200/**/apps/**/ma

  signedToken = jwt.sign(this.token, this.key, { algorithm: 'RS256' });

  config = {
    schema: this.schema,
    url: `wss://${this.senseHost}/${this.proxyPrefix}/app/engineData`,
    // Notice how the signed JWT is passed in the 'Authorization' header using the
    // 'Bearer' schema:
    createSocket: (url) => new WebSocket(url,
      {
        headers: { Authorization: 'Bearer ' + this.signedToken }
      })
  };

  createEnigmaSession() {
    let session;
    if (session) {
      session.close();
    }

    session = enigma.create(this.config);
    session.on('traffic:*', (dir, data) => console.log(dir, data));
    return session;
  }

**Comment by julien-f** [comment]
This library expose the standard WebSocket API in browsers, please [use it correctly](https://developer.mozilla.org/en-US/docs/Web/API/WebSocket/WebSocket).

I don't know how you can pass a bearer token to the request, after quick look on the Internet, it appears you cannot.
