### ISSUE TITLE
plans for ws 8.x?

### ISSUE THREAD

**Issue by wh0** [heineiuo/isomorphic-ws#21]
In the `ws` npm package, major version 8 brings some significant divergence from browser web sockets, in that messages with text data now present the data as a Buffer instead of a string. See here https://github.com/websockets/ws/commit/e173423c180dc1e4e6ee8938d9e4376a7a8b9757

I'm wondering if isomorphic-ws will do something to reconcile this with the browser version that gives a string.

**Comment by heineiuo** [comment]
Thanks @wh0 ! I guess a buffer polyfill for browser can fix this or not. I will try to find a solution later.

**Comment by wh0** [comment]
they've clarified that the change from string to buffers doesn't affect the browser-style `.onmessage` or `.addEventListener`, so use with this won't be affected

https://github.com/websockets/ws/issues/1942#issuecomment-912910348
