### ISSUE TITLE
Make export interface for NodeJS and browser the same

### ISSUE THREAD

**Issue by avkos** [heineiuo/isomorphic-ws#23]
for now, an export interface looks like

**for browser**
`import WebSocket from 'isomorphic-ws'`

**for NodeJS**
`import {WebSocket} from 'isomorphic-ws'`

It will be nice to have the same interface for browser and NodeJS

**Comment by heineiuo** [comment]
> for now, an export interface looks like
> 
> **for browser** `import WebSocket from 'isomorphic-ws'`
> 
> **for NodeJS** `import {WebSocket} from 'isomorphic-ws'`
> 
> It will be nice to have the same interface for browser and NodeJS

I don't think `import {WebSocket} from 'isomorphic-ws'` will work. Did you used it with Webpack?


The example code works for both browser and node:
https://github.com/heineiuo/isomorphic-ws/blob/0796a34cb4a5339ea39a4d335dcd9c6619c8b624/example/webpack/app.js#L1-L4


You can change this line to `target: 'node'` to see if it works for node:
https://github.com/heineiuo/isomorphic-ws/blob/0796a34cb4a5339ea39a4d335dcd9c6619c8b624/example/webpack/webpack.config.js#L11

**Comment by avkos** [comment]
I use isomorphic-ws in the library which anyone can use on the web and NodeJS.
so in my code, I have this line:
`import {WebSocket} from 'isomorphic-ws' `
and it works in NodeJS but in browser `WebSocket is undefined`

**Comment by avkos** [comment]
yes. you a right need to use this option for both
` import WebSocket from 'isomorphic-ws' `
