### ISSUE TITLE
It's alive? 😟

### ISSUE THREAD

**Issue by JoCat** [heineiuo/isomorphic-ws#24]
It appears that support for this package has been discontinued. It's a pity because there are not enough actual edits to support ES modules.
It will be great if the work in this repository resumes.
Just in case, I made [my package](https://github.com/JoCat/modern-isomorphic-ws) with some edits, you never know it will be useful to someone.

**Comment by heineiuo** [comment]
#20 did not merged because it has some errors waiting to be solved. I will try to release a new version with es module ASAP.

**Comment by JoCat** [comment]
Okay, in that case, you can see how it is implemented by me. The library works correctly both in the browser and in node 😉
