### ISSUE TITLE
The `ws` module no longer exposes the standard API for onmessage/onclose events

### ISSUE THREAD

**Issue by ThisIsMissEm** [heineiuo/isomorphic-ws#25]
See: https://github.com/websockets/ws/releases/tag/8.0.0

Previously it used the same API as the client standard, but now it needs you to specifically decode messages:

```
websocket.on('message', function message(data, isBinary) {
  const message = isBinary ? data : data.toString();
  // Continue as before.
});
```

**Comment by ThisIsMissEm** [comment]
Actually, looking closer, it looks like the release notes may have been slightly confusing / misleading: it seems only the events emitted are now non-standard, so `on("message", (data, isBinary) => {})`, but the `onmessage` handlers are still standard: https://github.com/websockets/ws/blob/5e4149ec6a82e0367a925881abca5667667030e9/lib/event-target.js#L193-L200

@lpinca could you confirm this API change?

**Comment by lpinca** [comment]
Correct, and it has always been like this (even before `ws@8.0.0`). Only listeners added via the `EventTarget` interface receives "standard" `Event`s.
